[project]
name = "dist-to-roads"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geojson>=3.2.0",
    "geopandas>=1.1.0",
    "numpy>=2.2.6",
    "osmium>=4.0.2",
    "pandas>=2.2.3",
    "pyproj>=3.7.1",
]
